### ISSUE TITLE
Graphique temporel des indispo

### ISSUE THREAD

**Issue by juliender** [ewoken/nuclear-monitor#4]
Est-ce qu'il est prévu de faire un graphique ( stacked bar chart ) des indisponibilités (ou inversement, des disponibilités) ?
Je l'ai déjà fait, mais Scala (et juste en local par curiosité avec la data RTE).

Ça serait proprice de l'intégrer sur ce site là, pour avoir les données en temps réel.
Je peux essayer de le faire, puis de faire une pull request, mais je suis débutant en Node et React

**Comment by misdoro** [comment]
ça existe chez https://energygraph.info/d/cM9gMNZ4k/availability-timeline?orgId=1

**Comment by juliender** [comment]
En effet, merci
Je rajoute le lien vers le graphiqu eagrégé : https://energygraph.info/d/uMjgqrW4z/aggregated-availability?orgId=1&from=now-2M%2Fd&to=now%2B16M%2Fd
