### ISSUE TITLE
https://nuclear-monitor.fr down

### ISSUE THREAD

**Issue by fayak** [ewoken/nuclear-monitor#5]
Hello,

Il semblerait que https://nuclear-monitor.fr soit down. La page charge en boucle avec "Une erreur est survenue, veuillez essayer dans quelques minutes"

**Comment by NathanRDN** [comment]
+1

**Comment by florianbusi** [comment]
+1

**Comment by mouette** [comment]
+1000 d'après Twitter ! On peut aider ?

**Comment by fayak** [comment]
C'est fix, merci beaucoup !
