### ISSUE TITLE
Masquer Fessenheim

### ISSUE THREAD

**Issue by Chivos** [ewoken/nuclear-monitor#8]
L'arrêt des 2 réacteurs étant définitif, il serait pertinent de les retirer.

**Comment by Isio4-tech** [comment]
Bonjour,

Ce serait dommage de ne pas pouvoir naviguer dans les archives passées de ces deux réacteurs. Dans l'idéal, il faudrait que le calcul de la disponibilité (nombre de reacteurs en service et puissance totale) tienne compte de la date de fermeture définitive...
Par contre, depuis le 22 novembre 2023, l'appli Web part en erreur dans le navigateur car depuis cette date, l'API RTE ne fournit plus la production de ces deux réacteurs. Mettre explicitement des zeros sur la production de ces deux réacteurs malgré l'absence de données ?

**Comment by Chivos** [comment]
Bonjour,

Oui je vois l'idée, mais finalement est-ce le but de nuclear-monitor que de servir d'archive des données de Fessenheim ?
Il doit y avoir de l'open data par ailleurs.

Le point de Fessenheim n'étant plus sur la carte, je clôture le sujet.
